### ISSUE TITLE
Is it still getting maintained? I can see the last update is 2 years ago

### ISSUE THREAD

**Issue by RajRoR** [jaipandya/fullcontacter#3]

**Comment by jaipandya** [comment]
Not maintained anymore, there is an official one if you want to use - https://github.com/fullcontact/fullcontact-api-ruby

**Comment by RajRoR** [comment]
It doesn't support batch API calls, thats the problem :(

## 

Thanks
Raj

Normal fingers, tiny keyboard - sent via Gmail Mobile
